ingress:
  rootDomain: de1.wpfq.fr

unboundRecursive:
  deployment:
    image:
      pullPolicy: Always
    replicaCount: 1
  config:
    logQueries: "yes"
    cacheMinTtl: 3600
    numThreads: 1

dohProxy:
  deployment:
    image:
      pullPolicy: Always
    replicaCount: 2

dohProxyAGH:
  deployment:
    image:
      pullPolicy: Always
    replicaCount: 2

agh:
  deployment:
    image:
      pullPolicy: Always
    replicaCount: 1